### PR TITLE
Dockerization

### PR DESCRIPTION
**Pull request by pmauduit**
This commit introduces a new maven profile which aims to make the docker image generation easier, following the conventions from the geOrchestra project.

It will require a datadir which is not migrated yet, see: https://github.com/pmauduit/config/tree/cadastrapp-docker & https://github.com/georchestra/datadir/pull/23

Note: the introduced dockerfile unpacks the cadastrapp webapp, so that it is easier to inject a jetty-env.xml file, for JNDI configuration.

Tested (compilation only) with the following command:

```
mvn clean package docker:build -Pdocker                                \
-DdockerDatadirScmUrl=scm:git:https://github.com/pmauduit/config.git   \
-DdockerDatadirScmVersion=cadastrapp-docker
```

Note: I made a first commit which `xmlint --format` the `pom.xml` file, with no func change, please focus of the second one for review.

### CODE REVIEW

**Comment by landryb** [comment]
looks good, would be nice to have actual runtime testing :p

**Comment by pmauduit** [comment]
> looks good, would be nice to have actual runtime testing :p

I can't, I don't have any cadastre db :(

**Comment by pierrejego** [comment]
Thank you Pierre,
I can't test from here, can someone test ?  If not, I will be able to test on the first week of August .

**Comment by landryb** [comment]
> I can't, I don't have any cadastre db :(

Really, you should get access to at least one commune for proper testing.

**Comment by pmauduit** [comment]
> Really, you should get access to at least one commune for proper testing.

I took the opportunity of working on another addon (urbanisme) for Rennes-metropole which requires webservices from cadastrapp, and it seemed to work. I think this can be merged with no harm on the current build process.

**Comment by landryb** [comment]
+1 then - but since pom.xml changed in the meantime in ff1220fe, now there are git conflicts..

**Comment by pmauduit** [comment]
rebased

**Pull request merged**
