### PR TITLE
convert to georchestra datadir model and build a debian/rpm package

### PR DESCRIPTION
**Pull request by landryb**
This PR allows to build a debian package, shipping cadastrapp.properties under /etc/georchestra/cadastrapp like all other georchestra webapps do now in master. Might also build an rpm package via the correct maven profile but untested here.

The only modification to actual code is to tell `CadController.java` to try reading classpath:cadastrapp.properties _then_ cadastrapp.properties in georchestra datadir - that also means that `georchestra.datadir` should be defined in tomcat env, but this is now required in master.

According to the docs in http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/context/annotation/PropertySource.html and http://stackoverflow.com/questions/30764534/resolving-placeholder-within-propertysource/30766461#30766461 this should just 'do the right thing' - untested at runtime yet.

### CODE REVIEW

**Comment by landryb** [comment]
Note that to also get the log4j.xml file from the georchestra datadir, i'll have to add a dependency on georchestra-commons jar... work in progress.

**Comment by landryb** [comment]
The two last commits try to load logback.xml from ${georchestra.datadir}/cadastrapp if georchestra.datadir is set, and fallbacks to WEB-INF/classes/logback.xml otherwise.

I considered adding a dependency on georchestra-commons to reuse the GeorchestraConfiguration bean, but since it isnt published yet on a maven repo this is awkward.. and i'm not sure itd be that useful for other purposes.

I also considered making /cadastrapp/ configurable in the webapp (e.g matching servlet ContextPath ?) but wasnt sure if it was worth it - note that it's also 'hardcoded' in https://github.com/landryb/cadastrapp/commit/cb16f010357c6a2a734ae6e0e09fb2db0cc870a3

Would like feedback from @pmauduit on the rationale :)

**Comment by pmauduit** [comment]
> Would like feedback from @pmauduit on the rationale :)

Looks good to me (supposing you runtime-tested the modifications), it should work because of using static members (which requires initialization as soon as the JVM is aware of the class, which should obviously be the case, since you added a listener-class into the web.xml)

**Comment by landryb** [comment]
Yes of course this was tested at runtime, both with and without georchestra.datadir set.

**Pull request merged**
