### PR TITLE
Use github actions for CI

### PR DESCRIPTION
**Pull request by landryb**
like what's done in the main repository, WIP for now, but more eyes welcome (poke @fvanderbiest) - i dont plan to work on the docker part, but if i can have something that publishes a working cadastrapp.deb for georchestra/ansible...

### CODE REVIEW

**Comment by landryb** [comment]
as of 7c0e299 it actually succeeds per https://github.com/landryb/cadastrapp/actions/runs/50111484. lots of chicken sacrifices involved.

**Comment by landryb** [comment]
and we have a .deb artifact in https://github.com/landryb/cadastrapp/actions/runs/50119525 - whoo. @pierrejego :)

**Comment by pierrejego** [comment]
Bien joué :)

**Comment by fvanderbiest** [comment]
Thanks !
@pmauduit will take care of the docker side.

**Pull request merged**
